### ISSUE TITLE
When I use nginx, I have some access problems

### ISSUE THREAD

**Issue by League2EB** [agmm/standalone-rpi#1]
## I'm sorry it was a misunderstanding. I fixed it

Thank you for contribution

~~I'm not used to using Caddy to perform SSL certificate configuration~~

~~I like using Nginx more~~

~~So I removed the content from docker-comemage.yml~~

```
caddy:
    image: caddy
    container_name: caddy-proxy
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    networks:
      - standardnotes_standalone
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/certs:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
```

~~Currently successful affiliate Standalone~~

~~I always run into this problem when I register through the [website](https://app.standardnotes.com/)~~
